title: tedla.dev
markdown: kramdown
collections:
  writing:
    output: true
    permalink: /writing/:path.html
  projects:
    output: true
    permalink: /projects/:path.html
kramdown:
  input: GFM
  syntax_highlighter: none
exclude:
  - README.md
  - vendor
  - vendor/bundle
  - Gemfile
  - Gemfile.lock
